package com.mlprograms.impostor;

/*
 * Copyright (c) 2024 by Max Lemberg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.util.Arrays;
import java.util.List;

public class RandomThingList {
    public static final List<String> animalList = Arrays.asList(
            "Hund",
            "Katze",
            "Spatz",
            "Taube",
            "Amsel",
            "Goldfisch",
            "Forelle",
            "Hai",
            "Maus",
            "Ratte",
            "Kaninchen",
            "Eichhörnchen",
            "Hirsch",
            "Elefant",
            "Giraffe",
            "Löwe",
            "Tiger",
            "Bär",
            "Affe",
            "Pinguin",
            "Blauwal",
            "Schwertwal",
            "Delphin",
            "Schaf",
            "Ziege",
            "Schwein",
            "Kuh",
            "Pferd",
            "Esel",
            "Ente",
            "Gans",
            "Huhn",
            "Truthahn",
            "Adler",
            "Falke",
            "Frosch",
            "Schlange",
            "Krokodil",
            "Schildkröte",
            "Krabbe",
            "Hummer",
            "Spinne",
            "Biene",
            "Schmetterling",
            "Libelle",
            "Schnecke",
            "Fliege",
            "Marienkäfer",
            "Eidechse",
            "Hai",
            "Seestern",
            "Seehund",
            "Robbe",
            "Gorilla",
            "Orang-Utan",
            "Nashorn",
            "Flusspferd",
            "Zebra",
            "Känguru",
            "Koala",
            "Otter",
            "Fuchs",
            "Dachs",
            "Marder",
            "Wiesel",
            "Igel",
            "Krähe",
            "Elster",
            "Ameise",
            "Wespe",
            "Hornisse",
            "Heuschrecke",
            "Tausendfüßler",
            "Käfer",
            "Schabe",
            "Guppy",
            "Barrakuda",
            "Seepferdchen",
            "Sardine",
            "Aal",
            "Rochen",
            "Ochse",
            "Büffel",
            "Murmeltier",
            "Pavian",
            "Faultier",
            "Luchs",
            "Frettchen",
            "Karpfen",
            "Forelle",
            "Thunfisch",
            "Marlin",
            "Krake",
            "Qualle",
            "Seeanemone",
            "Delfin",
            "Pottwal",
            "Buckelwal",
            "Weißer Hai",
            "Hammerhai",
            "Zackenbarsch",
            "Kugelfisch",
            "Stachelrochen",
            "Tintenfisch",
            "Muschel",
            "Auster",
            "Jakobsmuschel",
            "Seekuh",
            "Lachs",
            "Hering",
            "Seeteufel",
            "Kormoran",
            "Basstölpel",
            "Pelikan",
            "Geier",
            "Gazelle",
            "Gepard",
            "Hyäne",
            "Leopard",
            "Oryxantilope",
            "Springbock",
            "Warzenschwein",
            "Strauß",
            "Papagei",
            "Kakadu",
            "Kolibri",
            "Elch",
            "Rentier",
            "Wildschwein",
            "Dromedar",
            "Alpaka",
            "Lama",
            "Flamingo",
            "Kiwi (Vogel)",
            "Tasmanischer Teufel",
            "Schnabeltier",
            "Koalabär",
            "Wombat",
            "Tapir",
            "Nasenbär",
            "Stinktier",
            "Waschbär",
            "Opossum",
            "Koikarpfen",
            "Barsch",
            "Wels",
            "Heilbutt",
            "Garnelen",
            "Muscheln",
            "Krabben",
            "Sittich",
            "Wellensittich",
            "Dohle",
            "Elster",
            "Specht",
            "Sperling",
            "Star",
            "Kormoran",
            "Fink",
            "Grille",
            "Seeschnecke",
            "Tintenfisch",
            "Aal",
            "Barrakuda",
            "Lachs",
            "Hummer",
            "Seestern",
            "Frosch",
            "Molch",
            "Axolotl",
            "Tarantel",
            "Gottesanbeterin",
            "Tausendfüßer",
            "Regenwurm",
            "Skorpion",
            "Eidechse",
            "Chamäleon",
            "Waran",
            "Gürteltier",
            "Fledermaus",
            "Stachelschwein",
            "Flughund",
            "Gila-Monster",
            "Schneeleopard",
            "Wanderfalke",
            "Seelöwe",
            "Seeotter",
            "Manatee",
            "Manta-Rochen",
            "Hammerhai",
            "Wobbegong",
            "Muräne",
            "Beluga-Wal",
            "Oktopus",
            "Pelikan",
            "Kondor",
            "Kuckuck",
            "Kolkrabe",
            "Kolibri",
            "Hering",
            "Forelle",
            "Auster",
            "Muschel",
            "Tausendfüßler",
            "Nacktschnecke",
            "Geißelkröte",
            "Pantherchamäleon",
            "Siamkatze",
            "Gepard",
            "Mantarochen",
            "Schwertwal",
            "Schwarzes Nashorn",
            "Riesensalamander",
            "Narwal",
            "Mangusten",
            "Zibetkatze",
            "Walhai",
            "Gorilla",
            "Mandrill",
            "Kraken",
            "Hammerhai",
            "Nacktmull",
            "Seehund",
            "Eisbär",
            "Quokka",
            "Schwarzspitzenriffhai",
            "Gila-Krustenechse",
            "Dugong",
            "Fennek",
            "Weißkopfseeadler",
            "Arapaima",
            "Geisterfledermaus",
            "Schnabeltier",
            "Fischotter",
            "Warzenschwein",
            "Flughund",
            "Feuersalamander",
            "Gangesdelfin",
            "Gürteltier",
            "Nilpferd",
            "Riesenmaulhai",
            "Narwal",
            "Stachelrochen",
            "Riesenameisenbär",
            "Ozelot",
            "Nebelparder",
            "Gabelbock",
            "Riesenschnabeltier",
            "Regenbogenfisch",
            "Seepferdchen",
            "Riesenkalmar",
            "Riesenotter",
            "Kapuzineraffe",
            "Gila-Krustenechse",
            "Schnabeltier",
            "Riesengürteltier",
            "Seeadler",
            "Riesenschuppentier",
            "Felsenpinguin",
            "Riesenmanta",
            "Echte Flusskrebse",
            "Gangesdelfin",
            "Schneespringer",
            "Grönlandwal",
            "Kurzschnabeligel",
            "Serval",
            "Königspython",
            "Riesensalamander",
            "Goldener Löwe Tamarin",
            "Riesenfledermaus",
            "Geißelkröte",
            "Langschnabeligel",
            "Madagaskar-Taggecko",
            "Riesenameisenbär",
            "Moschusochse",
            "Serval",
            "Malaienbär",
            "Fossa",
            "Brillenpinguin",
            "Flughund",
            "Ameisenbär",
            "Flussdelfin",
            "Seelöwe",
            "Elch",
            "Alligator",
            "Tapir",
            "Fledermaus",
            "Bonobo",
            "Schimpanse",
            "Mungo",
            "Luchs",
            "Schleichkatze",
            "Tasmanischer Teufel",
            "Seeadler",
            "Königskobra",
            "Präriehund",
            "Känguru",
            "Riesentintenfisch",
            "Riesenseeadler",
            "Riesenalk",
            "Riesenmammut",
            "Riesenadler",
            "Riesengeier",
            "Riesenmungo",
            "Riesengorilla",
            "Riesendachs",
            "Riesenotter",
            "Riesenwaran",
            "Riesenpython",
            "Riesenspinne",
            "Riesenfliege",
            "Riesenbiene",
            "Riesenkäfer",
            "Riesenskorpion",
            "Riesenwespe",
            "Riesenameise",
            "Riesenkäfer",
            "Riesenkrabbe",
            "Riesenqualle",
            "Riesenschildkröte",
            "Riesenfrosch",
            "Riesenechse",
            "Riesenleguan",
            "Riesenschlange",
            "Riesenhai"
    );

    public static final List<String> soccerPlayerList = Arrays.asList(
            "Pelé",
            "Diego Maradona",
            "Lionel Messi",
            "Cristiano Ronaldo",
            "Johan Cruyff",
            "Michel Platini",
            "Franz Beckenbauer",
            "Ronaldo Nazário",
            "Zinedine Zidane",
            "Alfredo Di Stefano",
            "Ferenc Puskás",
            "Lev Yashin",
            "Bobby Charlton",
            "Eusébio",
            "George Best",
            "Garrincha",
            "Lothar Matthäus",
            "Paolo Maldini",
            "Marco van Basten",
            "Gerd Müller",
            "Roberto Baggio",
            "Ronaldinho",
            "Romário",
            "Thierry Henry",
            "Bobby Moore",
            "Karl-Heinz Rummenigge",
            "Ruud Gullit",
            "Johan Neeskens",
            "Franz Roth",
            "Uwe Seeler",
            "Fabio Cannavaro",
            "Alessandro Del Piero",
            "David Beckham",
            "Paolo Rossi",
            "Ruud van Nistelrooy",
            "Luis Figo",
            "Rivaldo",
            "Diego Forlán",
            "Michael Owen",
            "Peter Schmeichel",
            "Andriy Shevchenko",
            "Samuel Eto'o",
            "Michael Ballack",
            "Cafu",
            "Gary Lineker",
            "David Villa",
            "Xavi Hernández",
            "Andres Iniesta",
            "Oliver Kahn",
            "Francesco Totti",
            "Roberto Carlos",
            "Ronaldo Luís Nazário de Lima",
            "Ruud Krol",
            "Philipp Lahm",
            "Luis Suárez",
            "Neymar",
            "Sergio Agüero",
            "Iker Casillas",
            "Javier Zanetti",
            "Carles Puyol",
            "Fernando Torres",
            "Andrea Pirlo",
            "Patrick Vieira",
            "Javier Mascherano",
            "Andrés Escobar",
            "Hristo Stoichkov",
            "Gabriel Batistuta",
            "Juan Román Riquelme",
            "Pavel Nedvěd",
            "Lilian Thuram",
            "Raul Gonzalez",
            "Zlatan Ibrahimović",
            "Luis Enrique",
            "Carlos Valderrama",
            "Davor Šuker",
            "Marcel Desailly",
            "Dennis Bergkamp",
            "Fabien Barthez",
            "Gianluigi Buffon",
            "Edwin van der Sar",
            "Clarence Seedorf",
            "Henrik Larsson",
            "Eric Cantona",
            "Frank Rijkaard",
            "Didier Deschamps",
            "Patrick Kluivert",
            "Miroslav Klose",
            "Thomas Müller",
            "Jurgen Klinsmann",
            "Lothar Matthaus",
            "Paolo Rossi",
            "Thierry Henry",
            "Luka Modric",
            "Kaká",
            "Cristiano Ronaldo",
            "Lionel Messi",
            "Xavi Hernandez",
            "Zinedine Zidane",
            "Ronaldinho",
            "Andrés Iniesta",
            "Erling Haaland",
            "Achraf Hakimi",
            "David Alaba",
            "Romelu Lukaku",
            "Dusan Tadic",
            "Wilfried Zaha",
            "Danny Ings",
            "Jack Grealish",
            "Jadon Sancho",
            "Lucas Digne",
            "Isco",
            "Thomas Lemar",
            "Kingsley Coman",
            "Edinson Cavani",
            "Rodri",
            "Ferran Torres",
            "João Moutinho",
            "Ruben Neves",
            "Pedro Neto",
            "Diogo Jota",
            "João Cancelo",
            "Raphael Varane",
            "Kylian Mbappé",
            "Mauro Icardi",
            "Serge Gnabry",
            "Leon Goretzka",
            "Kai Havertz",
            "Timo Werner",
            "Julian Brandt",
            "Leroy Sané",
            "Milan Škriniar",
            "Lautaro Martínez",
            "Renato Sanches",
            "João Felix",
            "Raphaël Guerreiro",
            "Danilo Pereira",
            "Pepe",
            "William Carvalho",
            "Bernardo Silva",
            "Rúben Dias",
            "André Silva",
            "Nuno Mendes",
            "Diogo Dalot",
            "Rui Patrício",
            "Kasper Schmeichel",
            "Christian Eriksen",
            "Wilfred Ndidi",
            "Youri Tielemans",
            "James Maddison",
            "Caglar Söyüncü",
            "Hakan Çalhanoğlu",
            "Stefan de Vrij",
            "Mauro Camoranesi",
            "Fabio Quagliarella",
            "Gianluigi Donnarumma",
            "Lorenzo Insigne",
            "Ciro Immobile",
            "Alessandro Florenzi",
            "Nicolo Barella",
            "Leonardo Bonucci",
            "Giovanni Di Lorenzo",
            "Federico Bernardeschi",
            "Jordan Pickford",
            "Ben Chilwell",
            "Mason Mount",
            "Phil Foden",
            "Bukayo Saka",
            "John Stones",
            "Declan Rice",
            "Mason Greenwood",
            "Marcus Rashford",
            "Emiliano Martinez",
            "Alejandro Gómez",
            "José Giménez",
            "Federico Valverde",
            "Edin Džeko",
            "Dejan Kulusevski",
            "Emil Forsberg",
            "Robin Olsen",
            "Alexander Isak",
            "Pau Torres",
            "José Luis Gayà",
            "Mikel Oyarzabal",
            "Ferran Torres",
            "Koke",
            "Marcos Llorente",
            "Gerard Moreno",
            "Luis Enrique",
            "Adama Traoré",
            "David de Gea",
            "Nacho Fernández",
            "Jordi Alba",
            "Marco Asensio",
            "Thiago Alcantara",
            "Dani Carvajal",
            "Rodri",
            "Ferran Torres",
            "Marcos Alonso",
            "Eric Garcia",
            "Kepa Arrizabalaga"
    );

    public static final List<String> thingsList = Arrays.asList(
            "Schreibstift",
            "Notizbuch",
            "Tasse",
            "Teller",
            "Löffel",
            "Gabel",
            "Messer",
            "Kaffeetasse",
            "Teekanne",
            "Wasserglas",
            "Kühlschrank",
            "Fernseher",
            "Computer",
            "Handy",
            "Kopfhörer",
            "Schlüssel",
            "Geldbeutel",
            "Uhr",
            "Lampe",
            "Fernbedienung",
            "Kissen",
            "Decke",
            "Bücher",
            "Zeitung",
            "Toilettenpapier",
            "Zahnbürste",
            "Zahnpasta",
            "Handtuch",
            "Seife",
            "Shampoo",
            "Duschgel",
            "Spiegel",
            "Kamm",
            "Rasierer",
            "Klopapierhalter",
            "Mülleimer",
            "Tisch",
            "Stuhl",
            "Sofa",
            "Bett",
            "Kleiderschrank",
            "Schuhe",
            "Hemd",
            "Hose",
            "Jacke",
            "Schal",
            "Handschuhe",
            "Mütze",
            "Sonnenbrille",
            "Regenschirm",
            "Autoschlüssel",
            "Autositze",
            "Lenkrad",
            "Scheibenwischer",
            "Rückspiegel",
            "Tankdeckel",
            "Brieftasche",
            "Einkaufstasche",
            "Einkaufswagen",
            "Kaffeemaschine",
            "Teekessel",
            "Toaster",
            "Mikrowelle",
            "Backofen",
            "Herd",
            "Pfanne",
            "Topf",
            "Backblech",
            "Mixer",
            "Schneidebrett",
            "Tellerstapel",
            "Besteckkasten",
            "Salzstreuer",
            "Pfefferstreuer",
            "Gewürzregal",
            "Kühlschrankmagnet",
            "Geschirrtuch",
            "Schneebesen",
            "Kochlöffel",
            "Topflappen",
            "Kochbuch",
            "Küchentimer",
            "Nähnadel",
            "Faden",
            "Schere",
            "Nähmaschine",
            "Nähgarn",
            "Steckdose",
            "Stecker",
            "Verlängerungskabel",
            "Glühbirne",
            "Taschenlampe",
            "Kerzen",
            "Streichhölzer",
            "Feuerzeug",
            "Batterie",
            "Ladegerät",
            "USB-Kabel",
            "Notizblock",
            "Radiergummi",
            "Teekessel",
            "Küchentuch",
            "Backpapier",
            "Schneebesen",
            "Teigschaber",
            "Pfannenwender",
            "Knoblauchpresse",
            "Eieruhr",
            "Zitruspresse",
            "Waage",
            "Eierschneider",
            "Messbecher",
            "Käsemesser",
            "Flaschenöffner",
            "Dosenöffner",
            "Entsafter",
            "Reibe",
            "Kartoffelstampfer",
            "Nudelholz",
            "Backpinsel",
            "Ausstechformen",
            "Salatschleuder",
            "Sieb",
            "Schüsselset",
            "Kochbuchständer",
            "Toaster",
            "Sandwichmaker",
            "Waffeleisen",
            "Eierkocher",
            "Wasserkocher",
            "Mixer",
            "Standmixer",
            "Hochleistungsmixer",
            "Wassersprudler",
            "Espressomaschine",
            "Kaffeemühle",
            "French Press",
            "Mokkakanne",
            "Teebereiter",
            "Kaffeefilter",
            "Teesieb",
            "Thermoskanne",
            "Glaskanne",
            "Kaffeekanne",
            "Saftpresse",
            "Cocktailshaker",
            "Weinglas",
            "Bierglas",
            "Whiskyglas",
            "Martini-Glas",
            "Cocktailglas",
            "Longdrinkglas",
            "Bowle-Glas",
            "Sektglas",
            "Wasserglas",
            "Schnapsglas",
            "Weinkühler",
            "Eiskübel",
            "Servierplatte",
            "Schälchen",
            "Tortenplatte",
            "Besteckset",
            "Teekanne",
            "Kaffeekanne",
            "Serviettenhalter",
            "Gewürzmühle",
            "Vorratsdosen",
            "Brotkasten",
            "Geschirrspüler",
            "Küchenmaschine",
            "Eismaschine",
            "Pizzaofen",
            "Fritteuse",
            "Induktionsherd",
            "Dampfgarer",
            "Sous-vide-Garer",
            "Raclette-Grill",
            "Fondue-Set",
            "Wok",
            "Stabmixer",
            "Zwiebelschneider",
            "Nussknacker",
            "Flaschenverschluss",
            "Eiswürfelform",
            "Thermometer",
            "Schmortopf",
            "Bräter",
            "Pfannenset",
            "Grillschale",
            "Grillzange",
            "Rührschüssel",
            "Küchenwaage",
            "Küchenthermometer",
            "Schneidebrettset",
            "Geschirrtuchhalter",
            "Dosenhalter",
            "Einkaufstaschenhalter",
            "Gewürzregal",
            "Messerschärfer",
            "üchenwecker",
            "Kühlschrankmagnet",
            "Schneidbrett",
            "Mülleimer",
            "Brotmesser",
            "Teelicht",
            "Taschentuch",
            "Rucksack",
            "Regenschirm",
            "Geldbörse",
            "Mantel",
            "Gürtel",
            "Hosenbügel",
            "Wäschekorb",
            "Lappen",
            "Spülmittel",
            "Schwamm",
            "Salzstreuer",
            "Pfefferstreuer",
            "Besteck",
            "Trinkflasche",
            "Kochtopf",
            "Kochlöffel",
            "Abtropfsieb",
            "Brotdose",
            "Kaffeetasse",
            "Kuchenteller",
            "Müslischale",
            "Badehandtuch",
            "Strandtuch",
            "Sonnencreme",
            "Sonnenbrille",
            "Badeanzug/Badehose",
            "Strandtasche",
            "Sonnenschirm",
            "Picknickdecke",
            "Picknickkorb",
            "Regenschirm",
            "Sonnenbrille",
            "Buch",
            "Fernbedienung",
            "Kopfhörer",
            "Laptop",
            "Smartphone",
            "Fernseher",
            "Kamera",
            "Zahnbürste",
            "Haarbürste",
            "Spiegel",
            "Handtuch",
            "Seife",
            "Shampoo",
            "Conditioner",
            "Duschgel",
            "Zahnpasta",
            "Rasierer",
            "Toilettenpapier",
            "Handcreme",
            "Lippenbalsam",
            "Notizbuch",
            "Stift",
            "Taschentücher",
            "Sonnencreme",
            "Medikamente",
            "Laptop-Ladegerät",
            "Telefonladegerät",
            "Armbanduhr",
            "Schlüsselbund",
            "Rucksack",
            "Geldbörse",
            "Geldbeutel",
            "Taschenlampe",
            "Feuerzeug",
            "Streichhölzer",
            "Batterien",
            "Ladegerät",
            "Staubsauger",
            "Besen",
            "Schaufel",
            "Eimer",
            "Reinigungstücher",
            "Kleiderbügel",
            "Wäschekorb",
            "Staubtuch",
            "Müllbeutel",
            "Luftpumpe",
            "Fahrradschloss",
            "Sonnenschirm",
            "Picknickdecke",
            "Yogamatte",
            "Reisepass",
            "Reiseführer",
            "Handdesinfektionsmittel",
            "Erste-Hilfe-Set",
            "Taschenmesser",
            "Kreditkarte",
            "Ausweis",
            "Schlafsack",
            "Kissen",
            "Decke",
            "Zelt",
            "Campingstuhl",
            "Wanderrucksack",
            "Wanderkarte",
            "Wanderstöcke",
            "Kletterseil",
            "Klettergurt",
            "Helm",
            "Skistöcke",
            "Skibrille",
            "Skihelm",
            "Snowboard",
            "Schlittschuhe",
            "Schwimmbrille",
            "Badetuch",
            "Strandtasche",
            "Strandtuch",
            "Schwimmring",
            "Rettungsweste",
            "Surfbrett",
            "Taucherbrille",
            "Schnorchel",
            "Sonnenschutzkleidung",
            "Angeln",
            "Angelrute",
            "Köderbox",
            "Zeltstangen",
            "Trillerpfeife",
            "Kompass",
            "Stirnlampe",
            "Rettungsboje",
            "Pflaster",
            "Sportuhr",
            "Sporttasche",
            "Yogablock",
            "Basketball",
            "Fußball"
    );

    public static final List<String> foodList = Arrays.asList(
            "Ketchup",
            "Senf",
            "Mayonnaise",
            "Olivenöl",
            "Essig",
            "Honig",
            "Marmelade",
            "Erdnussbutter",
            "Nutella",
            "Reis",
            "Nudeln",
            "Mehl",
            "Zucker",
            "Haferflocken",
            "Cornflakes",
            "Kartoffeln",
            "Zwiebeln",
            "Knoblauch",
            "Tomaten",
            "Gurken",
            "Paprika",
            "Karotten",
            "Äpfel",
            "Bananen",
            "Orangen",
            "Trauben",
            "Wassermelone",
            "Ananas",
            "Erdbeeren",
            "Himbeeren",
            "Blaubeeren",
            "Mangos",
            "Avocados",
            "Brokkoli",
            "Spinat",
            "Salat",
            "Kohl",
            "Sellerie",
            "Aubergine",
            "Zucchini",
            "Pilze",
            "Bohnen",
            "Linsen",
            "Erbsen",
            "Mais",
            "Thunfisch",
            "Lachs",
            "Garnelen",
            "Hähnchenbrust",
            "Rinderhackfleisch",
            "Schweinekotelett",
            "Speck",
            "Eier",
            "Milch",
            "Joghurt",
            "Butter",
            "Käse",
            "Quark",
            "Sahne",
            "Frischkäse",
            "Schokolade",
            "Kekse",
            "Apfel",
            "Banane",
            "Orange",
            "Erdbeere",
            "Blaubeeren",
            "Himbeeren",
            "Weintrauben",
            "Wassermelone",
            "Ananas",
            "Mango",
            "Avocado",
            "Birne",
            "Pfirsich",
            "Kiwi",
            "Zitrone",
            "Papaya",
            "Granatapfel",
            "Aprikose",
            "Kirschen",
            "Feigen",
            "Datteln",
            "Nektarine",
            "Grapefruit",
            "Melone",
            "Erdnüsse",
            "Mandeln",
            "Walnüsse",
            "Haselnüsse",
            "Cashewnüsse",
            "Pistazien",
            "Macadamianüsse",
            "Pekannüsse",
            "Paranüsse",
            "Sonnenblumenkerne",
            "Kürbiskerne",
            "Leinsamen",
            "Chiasamen",
            "Sesamsamen",
            "Quinoa",
            "Bulgur",
            "Couscous",
            "Hirse",
            "Haferflocken",
            "Gerste",
            "Roggen",
            "Dinkel",
            "Mais",
            "Reis",
            "Weizen",
            "Kamut",
            "Buchweizen",
            "Rote Bohnen",
            "Schwarze Bohnen",
            "Kidneybohnen",
            "Kichererbsen",
            "Linsen",
            "Erbsen",
            "Sojabohnen",
            "Tofu",
            "Tempeh",
            "Seitan",
            "Sojamilch",
            "Mandelmilch",
            "Hafermilch",
            "Reismilch",
            "Kokosmilch",
            "Kuhmilch",
            "Ziegenmilch",
            "Schafmilch",
            "Joghurt",
            "Käse",
            "Butter",
            "Margarine",
            "Olivenöl",
            "Rapsöl",
            "Sonnenblumenöl",
            "Kokosöl",
            "Avocadoöl",
            "Leinöl",
            "Sesamöl",
            "Walnussöl",
            "Sojasauce",
            "Balsamico-Essig",
            "Apfelessig",
            "Rotweinessig",
            "Weißweinessig",
            "Senf",
            "Ketchup",
            "Mayonnaise",
            "Hummus",
            "Guacamole",
            "Salsa",
            "Pesto",
            "Tapenade",
            "Baba Ghanoush",
            "Tzatziki",
            "Baba Ganoush",
            "Kimchi",
            "Sauerkraut",
            "Sambal"
    );
}
